/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include <gfx.h>
#include "gui.h"
#include "gui_helpers.h"
#include "gui_router.h"


int main(int argc, char* argv[])
{
	(void)argc;
	(void)argv;

    guiInit ();

	while (1) {
        guiWindow_EventLoop(5000);
	}

	return 0;
}


