/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define DD 0
#define GROUP_DEFAULT 1

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerMainFrame;
extern GHandle ghContainerStatus;
extern GHandle ghImagebox1_1;
extern GHandle ghLabelSsid;
extern GHandle ghLabelBatt;
extern GHandle ghLabelTime;
extern GHandle ghImagebox1;
extern GHandle ghContainerNavkeys;
extern GHandle ghLabel6;
extern GHandle ghButtonClose;
extern GHandle ghButtonMenu;
extern GHandle ghContainerMainMenu;
extern GHandle ghButtonPlayer;
extern GHandle ghButtonRecognize;
extern GHandle ghButtonWeather;
extern GHandle ghButtonRemote;
extern GHandle ghButtonSettings;
extern GHandle ghContainerWifiSettings;
extern GHandle ghKeyboard1;
extern GHandle ghInputPassword;
extern GHandle ghInputSSID;
extern GHandle ghLabel5_1;
extern GHandle ghLabel5;
extern GHandle ghContainerBrowseFile;
extern GHandle ghListFiles;
extern GHandle ghLabel5;
extern GHandle ghContainerAudioPlayer;
extern GHandle ghLabel5;
extern GHandle ghButton1;
extern GHandle ghButton1_1;
extern GHandle ghButton1_2;
extern GHandle ghContainerRemoteControl;
extern GHandle ghLabel5;
extern GHandle ghButtonRemotePower;
extern GHandle ghButtonRemoteVolumePlus;
extern GHandle ghButtonRemoteVolumeMinus;
extern GHandle ghButtonRemoteProgMinus;
extern GHandle ghButtonRemoteProgPlus;
extern GHandle ghButtonRemotePrev;
extern GHandle ghButtonRemotePause;
extern GHandle ghButtonRemoteNext;
extern GHandle ghLabel5_2;
extern GHandle ghImagebox3;
extern GHandle ghContainerWeather;
extern GHandle ghLabel5;
extern GHandle ghImagebox2;
extern GHandle ghImagebox2_1;
extern GHandle ghImagebox2_2;
extern GHandle ghLabelTemperature;
extern GHandle ghLabelHumidity;
extern GHandle ghLabelPressure;
extern GHandle ghContainerRecognizer;
extern GHandle ghButtonStartSpeech;
extern GHandle ghProgressRecording;
extern GHandle ghEnableVAD;
extern GHandle ghLabelRecognizeResult;
extern GHandle ghLabelRecognizeResult2;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);

#endif /* _GUI_H_ */

